### PR TITLE
feat: Implement dashboard

### PR DESCRIPTION
**Pull request by nam-t24**
All info for dashboard is finished and all pages has been flushed out. Only need to add extra food info/allergies but we can deploy the main food for now.

### CODE REVIEW

**Comment by abdullah50053** [comment]
Need conflicts fixed

**Comment by nam-t24** [comment]
> Need conflicts fixed

I'll get to those soon

**Comment by WillieCubed** [comment]
#### 📝 Changed routes:


| [**…ents/AnnouncementCards**](https://hackportal-hackutd-2w32i4i9h-acmutd.vercel.app/dashboard/Components/AnnouncementCards) | [**…rd/Components/ClubCard**](https://hackportal-hackutd-2w32i4i9h-acmutd.vercel.app/dashboard/Components/ClubCard) |
|:-:|:-:|
|<a href="https://hackportal-hackutd-2w32i4i9h-acmutd.vercel.app/dashboard/Components/AnnouncementCards">Screenshot of /dashboard/Components/AnnouncementCards</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/wYonrELJE7kqTQSUSEvXSQqTyZGgR5vd4UXtGZqt6OXQ2Zidg3t_EEwC1mx08zIvK1PVey-j-TA9Dd44Np7JZw.png">(view full size)</a> |<a href="https://hackportal-hackutd-2w32i4i9h-acmutd.vercel.app/dashboard/Components/ClubCard">Screenshot of /dashboard/Components/ClubCard</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/EEovca-TFCblcAZyRgVZiyjNn89HT9SXGseikKwpFEsBCFy6hEE7c87zMBAtb38un5mBcoN5HKmuJZFJrwSLXw.png">(view full size)</a> |



| [**…Components/MentorCard1**](https://hackportal-hackutd-2w32i4i9h-acmutd.vercel.app/dashboard/Components/MentorCard1) | [**…Components/MentorCard3**](https://hackportal-hackutd-2w32i4i9h-acmutd.vercel.app/dashboard/Components/MentorCard3) |
|:-:|:-:|
|<a href="https://hackportal-hackutd-2w32i4i9h-acmutd.vercel.app/dashboard/Components/MentorCard1">Screenshot of /dashboard/Components/MentorCard1</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/ZoJr_-wyF0ll4AzOpyvh1s0cpEBCpUrHlwuw5MTkOplni4ecOf9UihrvxdYS44uwsFd4a9405BhZXTVnCi639Q.png">(view full size)</a> |<a href="https://hackportal-hackutd-2w32i4i9h-acmutd.vercel.app/dashboard/Components/MentorCard3">Screenshot of /dashboard/Components/MentorCard3</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/-eNpAnLpBNOlifRygc5HJX0585M2VmTgV4kekU3CQ-z75rzWSHaE5q5dDyBpTD0HifqBblR1ou3Rfu-JgehBvw.png">(view full size)</a> |



| [**…ts/SpotlightCardScroll**](https://hackportal-hackutd-2w32i4i9h-acmutd.vercel.app/dashboard/Components/SpotlightCardScroll) | [**/dashboard/hackerpack**](https://hackportal-hackutd-2w32i4i9h-acmutd.vercel.app/dashboard/hackerpack) |
|:-:|:-:|
|<a href="https://hackportal-hackutd-2w32i4i9h-acmutd.vercel.app/dashboard/Components/SpotlightCardScroll">Screenshot of /dashboard/Components/SpotlightCardScroll</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/vBoQIv1sHit8zNaucQirkLLPSRKUEQUwKZROxCbEw-5ZW15R2VvKRyk3onVCFpO1qVKm86D_qKaryOf-En3SAQ.png">(view full size)</a> |<a href="https://hackportal-hackutd-2w32i4i9h-acmutd.vercel.app/dashboard/hackerpack">Screenshot of /dashboard/hackerpack</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/VNtFJ3lHUNa6NhXYAxhROwtj_rhjsXrazMqk2VpRrOf-tQn85mYDt6dUxYqpKAOcTxrADp52nCoVuhYxkSY4mQ.png">(view full size)</a> |



And 2 other routes:
- [**/dashboard**](https://hackportal-hackutd-2w32i4i9h-acmutd.vercel.app/dashboard)
- [**/speakers**](https://hackportal-hackutd-2w32i4i9h-acmutd.vercel.app/speakers)



Commit 4a757221841d8f461e4e290eccc746dd2c16e303 (https://hackportal-hackutd-2w32i4i9h-acmutd.vercel.app).

**Comment by nam-t24** [comment]
PR and branch has been merged into chore/merge branch

**Pull request closed without merging**
