### PR TITLE
fix: Resolve schedule inconsistencies with master spreadsheet

### PR DESCRIPTION
**Pull request by WillieCubed**
We're still waiting on some information about the opening ceremony.

### CODE REVIEW

**Comment by abdullah50053** [comment]
Add check in close/ late registration close 
Screen Shot 2021-11-10 at 8 00 27 PM

Fix walk-in registration time end to before the opening ceremony
Screen Shot 2021-11-10 at 8 01 53 PM

Why is the closing ceremony on Saturday
Screen Shot 2021-11-10 at 8 02 23 PM

Remove snacks
Screen Shot 2021-11-10 at 8 02 59 PM

Debrief is not a social
Screen Shot 2021-11-10 at 8 03 17 PM

**Comment by abdullah50053** [comment]
Also in speakers tab there are 2 cards of the same speaker
Screen Shot 2021-11-10 at 8 04 26 PM

**Comment by WillieCubed** [comment]
#### 📝 Changed routes:


| [**/calendar**](https://hackportal-hackutd-oxz4e2ckr-acmutd.vercel.app/calendar) |
|:-:|
|<a href="https://hackportal-hackutd-oxz4e2ckr-acmutd.vercel.app/calendar">Screenshot of /calendar</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/pP0BfT7NWB_95qkflH0LkXN6mUfyNtyCb4uJZZSG-Rt7NEN7AvmL1cT9-h-PoszJx_jV3yjbs1jrKByfDXBfBw.png">(view full size)</a> |







Commit d72c966b8fe33176222f0dd3507a974cd861c454 (https://hackportal-hackutd-oxz4e2ckr-acmutd.vercel.app).

**Comment by abdullah50053** [comment]
Opening ceremony only 30 mins?
Screen Shot 2021-11-10 at 8 33 53 PM

Also, 2x speaker bug reintroduced
Screen Shot 2021-11-10 at 8 36 10 PM

**Review by abdullah50053 — APPROVED** [review]
lgtm

**Pull request merged**
